### PR TITLE
Port upstream libdeflate 1.18

### PR DESCRIPTION
**Pull request by andreittr**
Includes patch to adapt intrinsics handling to the Unikraft build.

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
@andreittr I get this when trying to build (helloworld, libdeflate and intel-intrinsics)

```
origin/libdeflate-1.18/lib/arm/adler32_impl.h:51:12: fatal error: arm_neon.h: No such file or directory
   51 | #  include <arm_neon.h>
      |            ^~~~~~~~~~~~
```

Any library I'm missing?

**Comment by andreittr** [comment]
> @andreittr I get this when trying to build (helloworld, libdeflate and intel-intrinsics)
> 
> ```
> origin/libdeflate-1.18/lib/arm/adler32_impl.h:51:12: fatal error: arm_neon.h: No such file or directory
>    51 | #  include <arm_neon.h>
>       |            ^~~~~~~~~~~~
> ```
> 
> Any library I'm missing?

@StefanJum I believe you need https://github.com/unikraft/lib-arm-intrinsics in your libs path, although I haven't tested on arm yet, stuff may break.

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
All good, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
